export type StatusInscricao =
  | "Na fila"
  | "Chamado e aceito"
  | "Chamado e não aceito"
  | "Já fez o retiro"
  | "Pediu para excluir da lista";

export const STATUS_OPTIONS: StatusInscricao[] = [
  "Na fila",
  "Chamado e aceito",
  "Chamado e não aceito",
  "Já fez o retiro",
  "Pediu para excluir da lista",
];

export const MODALIDADES = [
  "Manancial Innocence (5 a 7 anos)",
  "Manancial Kids (8 a 10 anos)",
  "Manancial Teens (11 a 13 anos)",
  "Manancial New Life (15 a 17 anos)",
  "Manancial Power (18 a 25 anos)",
  "Manancial Sênior (a partir de 26 anos)",
  "Manancial Alliance",
] as const;

export type Modalidade = (typeof MODALIDADES)[number];

// Faixa etária permitida por modalidade (inclusivo).
// Alliance: público adulto (mesma faixa do Sênior, com requisitos extras).
export const MODALIDADE_FAIXA_ETARIA: Record<Modalidade, { min: number; max: number | null }> = {
  "Manancial Innocence (5 a 7 anos)": { min: 5, max: 7 },
  "Manancial Kids (8 a 10 anos)": { min: 8, max: 10 },
  "Manancial Teens (11 a 13 anos)": { min: 11, max: 13 },
  "Manancial New Life (15 a 17 anos)": { min: 15, max: 17 },
  "Manancial Power (18 a 25 anos)": { min: 18, max: 25 },
  "Manancial Sênior (a partir de 26 anos)": { min: 26, max: null },
  "Manancial Alliance": { min: 26, max: null },
};

export function calcularIdade(dataNascimentoIso: string, hoje: Date = new Date()): number | null {
  if (!dataNascimentoIso) return null;
  const nasc = new Date(dataNascimentoIso);
  if (Number.isNaN(nasc.getTime())) return null;
  let idade = hoje.getFullYear() - nasc.getFullYear();
  const m = hoje.getMonth() - nasc.getMonth();
  if (m < 0 || (m === 0 && hoje.getDate() < nasc.getDate())) idade--;
  return idade;
}

export function modalidadesPermitidasPorIdade(idade: number | null): Modalidade[] {
  if (idade === null) return [...MODALIDADES];
  return MODALIDADES.filter((m) => {
    const { min, max } = MODALIDADE_FAIXA_ETARIA[m];
    if (idade < min) return false;
    if (max !== null && idade > max) return false;
    return true;
  });
}

export function cpfJaInscritoNaModalidade(
  retirantes: { cpf: string; modalidade: string }[],
  cpf: string,
  modalidade: string,
): boolean {
  const norm = (v: string) => v.replace(/\D/g, "");
  const alvo = norm(cpf);
  if (!alvo) return false;
  return retirantes.some((r) => norm(r.cpf) === alvo && r.modalidade === modalidade);
}

export function validarCpf(cpf: string): boolean {
  const d = cpf.replace(/\D/g, "");
  if (d.length !== 11) return false;
  if (/^(\d)\1{10}$/.test(d)) return false;
  const calc = (base: string, factor: number) => {
    let sum = 0;
    for (let i = 0; i < base.length; i++) sum += parseInt(base[i], 10) * (factor - i);
    const r = (sum * 10) % 11;
    return r === 10 ? 0 : r;
  };
  const dv1 = calc(d.slice(0, 9), 10);
  const dv2 = calc(d.slice(0, 10), 11);
  return dv1 === parseInt(d[9], 10) && dv2 === parseInt(d[10], 10);
}



export const TAMANHOS_CAMISA = ["PP", "P", "M", "G", "GG", "XG", "XGG"] as const;

export type Retirante = {
  id: string;
  nome: string;
  cpf: string;
  data_nascimento: string;
  whatsapp: string;
  email: string;
  tamanho_camisa: string;
  link_rede_social: string;
  paroquia: string;
  modalidade: string;
  ano_manancial_senior: string | null;
  tem_sacramento_matrimonio: boolean | null;
  restricoes_alimentares: string;
  alergias: string;
  contato_emergencia_nome: string;
  contato_emergencia_telefone: string;
  endereco: string;
  bairro: string;
  cidade: string;
  cep: string;
  status_inscricao: StatusInscricao;
  data_recusa_vaga: string | null;
  created_at: string;
  e_casado?: boolean | null;
  nome_conjuge?: string;
  motivo_inscricao?: string;
};

export const MOCK_RETIRANTES: Retirante[] = [
  {
    id: "1", nome: "Maria Aparecida Silva", cpf: "123.456.789-01",
    data_nascimento: "1985-03-12", whatsapp: "(48) 99999-1111",
    email: "maria@email.com", tamanho_camisa: "M",
    link_rede_social: "@mariasilva", paroquia: "Paróquia São José",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "João Silva", contato_emergencia_telefone: "(48) 98888-1111",
    endereco: "Rua das Flores, 123", bairro: "Centro",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-000",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-12T10:30:00Z",
  },
  {
    id: "2", nome: "Pedro Henrique Costa", cpf: "234.567.890-12",
    data_nascimento: "2010-07-22", whatsapp: "(48) 99999-2222",
    email: "pedro.mae@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Nenhuma",
    contato_emergencia_nome: "Ana Costa", contato_emergencia_telefone: "(48) 98888-2222",
    endereco: "Av. Brasil, 456", bairro: "Caldas da Imperatriz",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-100",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-04-15T14:20:00Z",
  },
  {
    id: "3", nome: "Lucas e Juliana Mendes", cpf: "345.678.901-23",
    data_nascimento: "1990-11-05", whatsapp: "(48) 99999-3333",
    email: "casal.mendes@email.com", tamanho_camisa: "G",
    link_rede_social: "@juliana.mendes", paroquia: "Paróquia Santo Antônio",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2024", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Roberto Mendes", contato_emergencia_telefone: "(48) 98888-3333",
    endereco: "Rua das Acácias, 78", bairro: "São Cristóvão",
    cidade: "Florianópolis", cep: "88040-000",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-18T09:10:00Z",
  },
  {
    id: "4", nome: "Sofia Albuquerque", cpf: "456.789.012-34",
    data_nascimento: "2018-01-30", whatsapp: "(48) 99999-4444",
    email: "sofia.pais@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia São José",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Camila Albuquerque", contato_emergencia_telefone: "(48) 98888-4444",
    endereco: "Rua das Palmeiras, 22", bairro: "Centro",
    cidade: "Palhoça", cep: "88130-000",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-05-01",
    created_at: "2026-04-20T16:00:00Z",
  },
  {
    id: "5", nome: "Rafael Oliveira", cpf: "567.890.123-45",
    data_nascimento: "2002-09-14", whatsapp: "(48) 99999-5555",
    email: "rafael@email.com", tamanho_camisa: "GG",
    link_rede_social: "instagram.com/rafa", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Nenhuma",
    contato_emergencia_nome: "Marta Oliveira", contato_emergencia_telefone: "(48) 98888-5555",
    endereco: "Rua XV de Novembro, 900", bairro: "Centro",
    cidade: "Florianópolis", cep: "88010-000",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "6", nome: "Beatriz Souza", cpf: "678.901.234-56",
    data_nascimento: "2008-06-08", whatsapp: "(48) 99999-6666",
    email: "bia@email.com", tamanho_camisa: "M",
    link_rede_social: "@biasouza", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Paulo Souza", contato_emergencia_telefone: "(48) 98888-6666",
    endereco: "Rua do Sol, 45", bairro: "Praia Comprida",
    cidade: "São José", cep: "88110-000",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-25T11:45:00Z",
  },
  {
    id: "7", nome: "Antônio Carlos Pereira", cpf: "789.012.345-67",
    data_nascimento: "1965-12-01", whatsapp: "(48) 99999-7777",
    email: "antonio@email.com", tamanho_camisa: "G",
    link_rede_social: "—", paroquia: "Paróquia São José",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - diabético", alergias: "Penicilina",
    contato_emergencia_nome: "Helena Pereira", contato_emergencia_telefone: "(48) 98888-7777",
    endereco: "Rua das Hortênsias, 12", bairro: "Centro",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-000",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-04-05T13:00:00Z",
  },
  {
    id: "8", nome: "Ana Beatriz Lima", cpf: "167.747.156-56",
    data_nascimento: "2008-10-14", whatsapp: "(48) 91437-8275",
    email: "ana.lima@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/beatriz", paroquia: "Paróquia Santo Antônio",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Natália Ferreira", contato_emergencia_telefone: "(48) 99701-4504",
    endereco: "Rua XV de Novembro, 458", bairro: "São Cristóvão",
    cidade: "Biguaçu", cep: "88139-934",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-12T15:09:59Z",
  },
  {
    id: "9", nome: "Carlos Eduardo Santos", cpf: "389.459.494-29",
    data_nascimento: "2018-04-27", whatsapp: "(48) 93665-5122",
    email: "carlos.santos@email.com", tamanho_camisa: "XGG",
    link_rede_social: "instagram.com/eduardo", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Bruno Teixeira", contato_emergencia_telefone: "(48) 93593-3908",
    endereco: "Rua da Praia, 251", bairro: "Campeche",
    cidade: "São José", cep: "88101-246",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-01-23T03:34:54Z",
  },
  {
    id: "10", nome: "Fernanda Oliveira", cpf: "871.867.714-24",
    data_nascimento: "2018-10-14", whatsapp: "(48) 95574-3167",
    email: "fernanda.oliveira@email.com", tamanho_camisa: "P",
    link_rede_social: "@fernanda", paroquia: "Paróquia Santa Terezinha",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Kleber Rangel", contato_emergencia_telefone: "(48) 98260-2733",
    endereco: "Rua das Hortênsias, 380", bairro: "Campeche",
    cidade: "Tijucas", cep: "88079-369",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-10T19:18:32Z",
  },
  {
    id: "11", nome: "Gabriel Henrique Costa", cpf: "472.818.583-45",
    data_nascimento: "2021-12-09", whatsapp: "(48) 98157-3695",
    email: "gabriel.costa@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Amendoim",
    contato_emergencia_nome: "Diego Pinheiro", contato_emergencia_telefone: "(48) 96356-9131",
    endereco: "Rua Brasil, 310", bairro: "Jurerê",
    cidade: "São José", cep: "88053-348",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-02-20T20:06:11Z",
  },
  {
    id: "12", nome: "Isabela Martins", cpf: "631.826.594-56",
    data_nascimento: "2016-09-13", whatsapp: "(48) 94651-1870",
    email: "isabela.martins@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - diabético", alergias: "Amendoim",
    contato_emergencia_nome: "Kleber Rangel", contato_emergencia_telefone: "(48) 91951-7490",
    endereco: "Rua São João, 100", bairro: "Campeche",
    cidade: "Brusque", cep: "88092-099",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-01-15T19:15:12Z",
  },
  {
    id: "13", nome: "João Pedro Almeida", cpf: "241.945.331-00",
    data_nascimento: "1994-04-02", whatsapp: "(48) 95485-8500",
    email: "joão.almeida@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/pedro", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2025", tem_sacramento_matrimonio: false,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Nenhuma",
    contato_emergencia_nome: "Daniel Moreira", contato_emergencia_telefone: "(48) 95760-3003",
    endereco: "Rua das Flores, 21", bairro: "Sertão do Ribeirão",
    cidade: "Rancho Queimado", cep: "88006-533",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-16T04:13:55Z",
  },
  {
    id: "14", nome: "Larissa Souza", cpf: "281.314.611-06",
    data_nascimento: "2019-02-02", whatsapp: "(48) 96959-1891",
    email: "larissa.souza@email.com", tamanho_camisa: "M",
    link_rede_social: "@larissa", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Rodrigo Cardoso", contato_emergencia_telefone: "(48) 93791-8137",
    endereco: "Rua Brasil, 490", bairro: "Barra da Lagoa",
    cidade: "Rancho Queimado", cep: "88173-734",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-02T23:48:37Z",
  },
  {
    id: "15", nome: "Lucas Mendes", cpf: "625.665.622-96",
    data_nascimento: "2020-07-26", whatsapp: "(48) 98451-5990",
    email: "lucas.mendes@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Júlio César Nunes", contato_emergencia_telefone: "(48) 94175-7371",
    endereco: "Rua das Acácias, 214", bairro: "São Cristóvão",
    cidade: "Biguaçu", cep: "88001-254",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-05-13T17:18:34Z",
  },
  {
    id: "16", nome: "Mariana Rocha", cpf: "778.952.235-34",
    data_nascimento: "2016-12-13", whatsapp: "(48) 98212-7279",
    email: "mariana.rocha@email.com", tamanho_camisa: "PP",
    link_rede_social: "@mariana", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Rafaela Gomes", contato_emergencia_telefone: "(48) 93914-8311",
    endereco: "Rua XV de Novembro, 804", bairro: "Jurerê",
    cidade: "Rancho Queimado", cep: "88040-221",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-02-20T17:53:31Z",
  },
  {
    id: "17", nome: "Matheus Silva", cpf: "225.641.749-22",
    data_nascimento: "2015-04-01", whatsapp: "(48) 93263-4621",
    email: "matheus.silva@email.com", tamanho_camisa: "M",
    link_rede_social: "@matheus", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Rodrigo Cardoso", contato_emergencia_telefone: "(48) 98850-7643",
    endereco: "Rua da Praia, 23", bairro: "São Cristóvão",
    cidade: "São José", cep: "88121-879",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-04-13",
    created_at: "2026-01-28T08:55:59Z",
  },
  {
    id: "18", nome: "Natália Ferreira", cpf: "292.954.588-77",
    data_nascimento: "2019-04-21", whatsapp: "(48) 91949-7795",
    email: "natália.ferreira@email.com", tamanho_camisa: "XGG",
    link_rede_social: "@natália", paroquia: "Paróquia São José",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Penicilina",
    contato_emergencia_nome: "Pedro Augusto Lima", contato_emergencia_telefone: "(48) 94565-6550",
    endereco: "Rua das Flores, 761", bairro: "Campeche",
    cidade: "São José", cep: "88126-486",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-30T14:05:52Z",
  },
  {
    id: "19", nome: "Pedro Augusto Lima", cpf: "564.233.334-83",
    data_nascimento: "2018-05-18", whatsapp: "(48) 97723-9260",
    email: "pedro.lima@email.com", tamanho_camisa: "XGG",
    link_rede_social: "—", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Isabela Martins", contato_emergencia_telefone: "(48) 99929-5099",
    endereco: "Rua São João, 81", bairro: "Caldas da Imperatriz",
    cidade: "Governador Celso Ramos", cep: "88008-896",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-05-14",
    created_at: "2026-04-20T03:19:31Z",
  },
  {
    id: "20", nome: "Rafaela Gomes", cpf: "632.847.747-34",
    data_nascimento: "2020-10-02", whatsapp: "(48) 95117-2103",
    email: "rafaela.gomes@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/gomes", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Sabrina Lopes", contato_emergencia_telefone: "(48) 96459-2189",
    endereco: "Rua do Sol, 232", bairro: "Jurerê",
    cidade: "Brusque", cep: "88010-221",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-18T22:12:53Z",
  },
  {
    id: "21", nome: "Rodrigo Cardoso", cpf: "817.562.345-89",
    data_nascimento: "2007-11-17", whatsapp: "(48) 98345-6712",
    email: "rodrigo.cardoso@email.com", tamanho_camisa: "G",
    link_rede_social: "@rodrigo", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Dipirona",
    contato_emergencia_nome: "Tiago Neves", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua das Hortênsias, 55", bairro: "Centro",
    cidade: "Florianópolis", cep: "88040-123",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-14T10:22:33Z",
  },
  {
    id: "22", nome: "Sofia Martins", cpf: "341.876.543-21",
    data_nascimento: "2011-03-22", whatsapp: "(48) 93456-7890",
    email: "sofia.martins@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Ursula Vieira", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua XV de Novembro, 312", bairro: "Campeche",
    cidade: "Palhoça", cep: "88130-456",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-05T16:44:12Z",
  },
  {
    id: "23", nome: "Thiago Ribeiro", cpf: "982.345.678-90",
    data_nascimento: "1995-08-30", whatsapp: "(48) 95678-9012",
    email: "thiago.ribeiro@email.com", tamanho_camisa: "GG",
    link_rede_social: "instagram.com/thiago", paroquia: "Paróquia São Sebastião",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - diabético", alergias: "Penicilina",
    contato_emergencia_nome: "Vinícius Paes", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua Brasil, 77", bairro: "Barra da Lagoa",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-789",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-01-08T09:33:27Z",
  },
  {
    id: "24", nome: "Amanda Barbosa", cpf: "456.789.012-34",
    data_nascimento: "2009-06-15", whatsapp: "(48) 97890-1234",
    email: "amanda.barbosa@email.com", tamanho_camisa: "P",
    link_rede_social: "@amanda", paroquia: "Paróquia Nossa Senhora Aparecida",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Bruno Teixeira", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua das Acácias, 144", bairro: "Praia Comprida",
    cidade: "São José", cep: "88110-567",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-04-22T12:11:45Z",
  },
  {
    id: "25", nome: "Bruno Teixeira", cpf: "567.890.123-45",
    data_nascimento: "1988-12-03", whatsapp: "(48) 99012-3456",
    email: "bruno.teixeira@email.com", tamanho_camisa: "G",
    link_rede_social: "instagram.com/bruno", paroquia: "Paróquia São João Batista",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2023", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Camila Duarte", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua do Sol, 66", bairro: "Sertão do Ribeirão",
    cidade: "Florianópolis", cep: "88060-234",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-28T08:59:01Z",
  },
  {
    id: "26", nome: "Camila Duarte", cpf: "678.901.234-56",
    data_nascimento: "2003-01-25", whatsapp: "(48) 91234-5678",
    email: "camila.duarte@email.com", tamanho_camisa: "M",
    link_rede_social: "@camila", paroquia: "Paróquia Santa Terezinha",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Daniel Moreira", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua das Flores, 198", bairro: "Centro",
    cidade: "Biguaçu", cep: "88150-345",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-12T14:27:18Z",
  },
  {
    id: "27", nome: "Daniel Moreira", cpf: "789.012.345-67",
    data_nascimento: "2017-07-08", whatsapp: "(48) 93456-7890",
    email: "daniel.moreira@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Eduarda Pinto", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua Brasil, 256", bairro: "Caldas da Imperatriz",
    cidade: "Águas Mornas", cep: "88170-678",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-05-08T11:03:42Z",
  },
  {
    id: "28", nome: "Eduarda Pinto", cpf: "890.123.456-78",
    data_nascimento: "2004-11-11", whatsapp: "(48) 94567-8901",
    email: "eduarda.pinto@email.com", tamanho_camisa: "G",
    link_rede_social: "@eduarda", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Nenhuma",
    contato_emergencia_nome: "Felipe Araújo", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua das Hortênsias, 33", bairro: "Barra da Lagoa",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-01-19T07:15:29Z",
  },
  {
    id: "29", nome: "Felipe Araújo", cpf: "901.234.567-89",
    data_nascimento: "2012-09-19", whatsapp: "(48) 95678-9012",
    email: "felipe.araújo@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/felipe", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Giovanna Monteiro", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua XV de Novembro, 412", bairro: "Jurerê",
    cidade: "São José", cep: "88120-456",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-04-29",
    created_at: "2026-04-01T18:37:55Z",
  },
  {
    id: "30", nome: "Giovanna Monteiro", cpf: "012.345.678-90",
    data_nascimento: "2021-05-14", whatsapp: "(48) 96789-0123",
    email: "giovanna.monteiro@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Amendoim",
    contato_emergencia_nome: "Henrique Freitas", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua da Praia, 88", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-05T13:48:01Z",
  },
  {
    id: "31", nome: "Henrique Freitas", cpf: "123.456.789-01",
    data_nascimento: "1992-02-28", whatsapp: "(48) 97890-1234",
    email: "henrique.freitas@email.com", tamanho_camisa: "GG",
    link_rede_social: "@henrique", paroquia: "Paróquia São José",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Ingrid Correia", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua das Flores, 167", bairro: "São Cristóvão",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-012",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-25T20:55:43Z",
  },
  {
    id: "32", nome: "Ingrid Correia", cpf: "234.567.890-12",
    data_nascimento: "2010-04-16", whatsapp: "(48) 98901-2345",
    email: "ingrid.correia@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/ingrid", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Dipirona",
    contato_emergencia_nome: "Júlio César Nunes", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua Brasil, 399", bairro: "Praia Comprida",
    cidade: "São José", cep: "88110-890",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-08T06:22:14Z",
  },
  {
    id: "33", nome: "Júlio César Nunes", cpf: "345.678.901-23",
    data_nascimento: "1980-10-05", whatsapp: "(48) 99012-3456",
    email: "júlio.nunes@email.com", tamanho_camisa: "G",
    link_rede_social: "—", paroquia: "Paróquia Santo Antônio",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2021", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Sim - diabético", alergias: "Amendoim",
    contato_emergencia_nome: "Karina Dias", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua das Acácias, 72", bairro: "Centro",
    cidade: "Florianópolis", cep: "88020-345",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-01-30T17:40:08Z",
  },
  {
    id: "34", nome: "Karina Dias", cpf: "456.789.012-34",
    data_nascimento: "2013-08-21", whatsapp: "(48) 90123-4567",
    email: "karina.dias@email.com", tamanho_camisa: "M",
    link_rede_social: "@karina", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Leonardo Farias", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua do Sol, 111", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-678",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-06T14:11:37Z",
  },
  {
    id: "35", nome: "Leonardo Farias", cpf: "567.890.123-45",
    data_nascimento: "2014-06-30", whatsapp: "(48) 91234-5678",
    email: "leonardo.farias@email.com", tamanho_camisa: "GG",
    link_rede_social: "instagram.com/leonardo", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Melissa Cunha", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua XV de Novembro, 555", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88110-234",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-18T09:55:22Z",
  },
  {
    id: "36", nome: "Melissa Cunha", cpf: "678.901.234-56",
    data_nascimento: "2006-01-12", whatsapp: "(48) 92345-6789",
    email: "melissa.cunha@email.com", tamanho_camisa: "P",
    link_rede_social: "@melissa", paroquia: "Paróquia Nossa Senhora Aparecida",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Nicolas Borges", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua das Flores, 300", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-890",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-04-14T16:33:01Z",
  },
  {
    id: "37", nome: "Nicolas Borges", cpf: "789.012.345-67",
    data_nascimento: "2015-03-03", whatsapp: "(48) 93456-7890",
    email: "nicolas.borges@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia São Sebastião",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Látex",
    contato_emergencia_nome: "Patrícia Ramos", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua Brasil, 444", bairro: "Sertão do Ribeirão",
    cidade: "Biguaçu", cep: "88150-012",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-01T11:22:47Z",
  },
  {
    id: "38", nome: "Patrícia Ramos", cpf: "890.123.456-78",
    data_nascimento: "1998-12-09", whatsapp: "(48) 94567-8901",
    email: "patrícia.ramos@email.com", tamanho_camisa: "G",
    link_rede_social: "@patrícia", paroquia: "Paróquia Santa Terezinha",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Quésia Moraes", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua das Hortênsias, 99", bairro: "Centro",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-456",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-08T08:44:59Z",
  },
  {
    id: "39", nome: "Quésia Moraes", cpf: "901.234.567-89",
    data_nascimento: "2018-07-18", whatsapp: "(48) 95678-9012",
    email: "quésia.moraes@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/moraes", paroquia: "Paróquia São João Batista",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Amendoim",
    contato_emergencia_nome: "Renan Pacheco", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua do Sol, 177", bairro: "Praia Comprida",
    cidade: "São José", cep: "88110-345",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-04-22",
    created_at: "2026-04-28T05:17:33Z",
  },
  {
    id: "40", nome: "Renan Pacheco", cpf: "012.345.678-90",
    data_nascimento: "2002-05-22", whatsapp: "(48) 96789-0123",
    email: "renan.pacheco@email.com", tamanho_camisa: "GG",
    link_rede_social: "@renan", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Sabrina Lopes", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua das Acácias, 288", bairro: "Barra da Lagoa",
    cidade: "Florianópolis", cep: "88060-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-01-12T10:48:12Z",
  },
  {
    id: "41", nome: "Sabrina Lopes", cpf: "123.456.789-01",
    data_nascimento: "2005-11-07", whatsapp: "(48) 97890-1234",
    email: "sabrina.lopes@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/sabrina", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Dipirona",
    contato_emergencia_nome: "Tiago Neves", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua XV de Novembro, 633", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-04T19:33:28Z",
  },
  {
    id: "42", nome: "Tiago Neves", cpf: "234.567.890-12",
    data_nascimento: "1991-09-01", whatsapp: "(48) 98901-2345",
    email: "tiago.neves@email.com", tamanho_camisa: "G",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Ursula Vieira", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua Brasil, 122", bairro: "São Cristóvão",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-234",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-08T15:27:55Z",
  },
  {
    id: "43", nome: "Ursula Vieira", cpf: "345.678.901-23",
    data_nascimento: "2019-01-17", whatsapp: "(48) 99012-3456",
    email: "ursula.vieira@email.com", tamanho_camisa: "PP",
    link_rede_social: "@ursula", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Látex",
    contato_emergencia_nome: "Vinícius Paes", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua das Flores, 88", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-123",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-02T12:15:44Z",
  },
  {
    id: "44", nome: "Vinícius Paes", cpf: "456.789.012-34",
    data_nascimento: "2017-08-08", whatsapp: "(48) 90123-4567",
    email: "vinícius.paes@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/paes", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Wesley Braga", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua do Sol, 345", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-890",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-04-06T08:33:17Z",
  },
  {
    id: "45", nome: "Wesley Braga", cpf: "567.890.123-45",
    data_nascimento: "1993-06-25", whatsapp: "(48) 91234-5678",
    email: "wesley.braga@email.com", tamanho_camisa: "GG",
    link_rede_social: "@wesley", paroquia: "Paróquia São Sebastião",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Penicilina",
    contato_emergencia_nome: "Xênia Andrade", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua das Acácias, 77", bairro: "Sertão do Ribeirão",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-01-22T14:44:01Z",
  },
  {
    id: "46", nome: "Xênia Andrade", cpf: "678.901.234-56",
    data_nascimento: "2000-10-10", whatsapp: "(48) 92345-6789",
    email: "xênia.andrade@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/andrade", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Yasmin Sales", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua XV de Novembro, 199", bairro: "Centro",
    cidade: "Florianópolis", cep: "88020-678",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-05-01",
    created_at: "2026-03-15T09:11:27Z",
  },
  {
    id: "47", nome: "Yasmin Sales", cpf: "789.012.345-67",
    data_nascimento: "2016-04-04", whatsapp: "(48) 93456-7890",
    email: "yasmin.sales@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia São José",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Nenhuma",
    contato_emergencia_nome: "Zélia Tavares", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua das Flores, 222", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-012",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-04-18T16:22:55Z",
  },
  {
    id: "48", nome: "Zélia Tavares", cpf: "890.123.456-78",
    data_nascimento: "1987-02-14", whatsapp: "(48) 94567-8901",
    email: "zélia.tavares@email.com", tamanho_camisa: "G",
    link_rede_social: "@zélia", paroquia: "Paróquia Nossa Senhora Aparecida",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2024", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Adriana Melo", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua Brasil, 11", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-345",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-25T11:07:19Z",
  },
  {
    id: "49", nome: "Adriana Melo", cpf: "901.234.567-89",
    data_nascimento: "2014-09-09", whatsapp: "(48) 95678-9012",
    email: "adriana.melo@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/melo", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Látex",
    contato_emergencia_nome: "Bernardo Rezende", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua das Hortênsias, 333", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-456",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-20T07:33:41Z",
  },
  {
    id: "50", nome: "Bernardo Rezende", cpf: "012.345.678-90",
    data_nascimento: "2012-12-12", whatsapp: "(48) 96789-0123",
    email: "bernardo.rezende@email.com", tamanho_camisa: "G",
    link_rede_social: "@bernardo", paroquia: "Paróquia Santa Terezinha",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Cecília Figueiredo", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua da Praia, 55", bairro: "Sertão do Ribeirão",
    cidade: "São José", cep: "88110-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-01-05T13:44:22Z",
  },
  {
    id: "51", nome: "Cecília Figueiredo", cpf: "123.456.789-01",
    data_nascimento: "2001-03-30", whatsapp: "(48) 97890-1234",
    email: "cecília.figueiredo@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/figueiredo", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Amendoim",
    contato_emergencia_nome: "Diego Pinheiro", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua XV de Novembro, 777", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-234",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-10T18:11:09Z",
  },
  {
    id: "52", nome: "Diego Pinheiro", cpf: "234.567.890-12",
    data_nascimento: "1996-07-07", whatsapp: "(48) 98901-2345",
    email: "diego.pinheiro@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Eliane Siqueira", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua do Sol, 444", bairro: "Barra da Lagoa",
    cidade: "Santo Amaro da Imperatriz", cep: "88140-789",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-02T10:55:33Z",
  },
  {
    id: "53", nome: "Eliane Siqueira", cpf: "345.678.901-23",
    data_nascimento: "1989-11-20", whatsapp: "(48) 99012-3456",
    email: "eliane.siqueira@email.com", tamanho_camisa: "G",
    link_rede_social: "@eliane", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2022", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Fábio Guimarães", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua das Acácias, 66", bairro: "São Cristóvão",
    cidade: "Florianópolis", cep: "88020-123",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-28T15:22:07Z",
  },
  {
    id: "54", nome: "Fábio Guimarães", cpf: "456.789.012-34",
    data_nascimento: "2013-05-05", whatsapp: "(48) 90123-4567",
    email: "fábio.guimarães@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/fábio", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Nenhuma",
    contato_emergencia_nome: "Heloísa Peixoto", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua Brasil, 288", bairro: "Jurerê",
    cidade: "São José", cep: "88120-678",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-02-12T09:38:44Z",
  },
  {
    id: "55", nome: "Heloísa Peixoto", cpf: "567.890.123-45",
    data_nascimento: "2008-08-18", whatsapp: "(48) 91234-5678",
    email: "heloísa.peixoto@email.com", tamanho_camisa: "M",
    link_rede_social: "@heloísa", paroquia: "Paróquia São José",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Amendoim",
    contato_emergencia_nome: "Igor Barros", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua das Flores, 111", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-890",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-24T11:05:17Z",
  },
  {
    id: "56", nome: "Igor Barros", cpf: "678.901.234-56",
    data_nascimento: "2009-02-03", whatsapp: "(48) 92345-6789",
    email: "igor.barros@email.com", tamanho_camisa: "G",
    link_rede_social: "instagram.com/igor", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Juliana Cruz", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua XV de Novembro, 999", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88110-123",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-04-30",
    created_at: "2026-01-17T08:22:31Z",
  },
  {
    id: "57", nome: "Juliana Cruz", cpf: "789.012.345-67",
    data_nascimento: "1997-04-12", whatsapp: "(48) 93456-7890",
    email: "juliana.cruz@email.com", tamanho_camisa: "P",
    link_rede_social: "@juliana", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Dipirona",
    contato_emergencia_nome: "Kleber Rangel", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua das Hortênsias, 222", bairro: "Sertão do Ribeirão",
    cidade: "Florianópolis", cep: "88060-456",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-22T14:18:29Z",
  },
  {
    id: "58", nome: "Kleber Rangel", cpf: "890.123.456-78",
    data_nascimento: "2011-06-22", whatsapp: "(48) 94567-8901",
    email: "kleber.rangel@email.com", tamanho_camisa: "GG",
    link_rede_social: "instagram.com/rangel", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Ana Beatriz Lima", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua do Sol, 789", bairro: "Centro",
    cidade: "São José", cep: "88120-890",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-05-14T16:44:01Z",
  },
  {
    id: "59", nome: "Larissa Souza", cpf: "901.234.567-89",
    data_nascimento: "2003-09-15", whatsapp: "(48) 95678-9012",
    email: "larissa.souza2@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia São José",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Nenhuma",
    contato_emergencia_nome: "Carlos Eduardo Santos", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua das Flores, 456", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-234",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-12T09:33:27Z",
  },
  {
    id: "60", nome: "Mariana Rocha", cpf: "012.345.678-90",
    data_nascimento: "2019-11-11", whatsapp: "(48) 96789-0123",
    email: "mariana.rocha2@email.com", tamanho_camisa: "PP",
    link_rede_social: "@mariana2", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Gabriel Henrique Costa", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua XV de Novembro, 888", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-345",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-02-28T12:11:45Z",
  },
  {
    id: "61", nome: "Matheus Silva", cpf: "123.456.789-01",
    data_nascimento: "2010-07-20", whatsapp: "(48) 97890-1234",
    email: "matheus.silva2@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/matheus2", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Dipirona",
    contato_emergencia_nome: "Isabela Martins", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua Brasil, 777", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-567",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-01T15:22:07Z",
  },
  {
    id: "62", nome: "Natália Ferreira", cpf: "234.567.890-12",
    data_nascimento: "2018-03-08", whatsapp: "(48) 98901-2345",
    email: "natália.ferreira2@email.com", tamanho_camisa: "P",
    link_rede_social: "@natália2", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "João Pedro Almeida", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua das Hortênsias, 444", bairro: "Sertão do Ribeirão",
    cidade: "São José", cep: "88110-678",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-10T18:22:14Z",
  },
  {
    id: "63", nome: "Pedro Augusto Lima", cpf: "345.678.901-23",
    data_nascimento: "2001-05-05", whatsapp: "(48) 99012-3456",
    email: "pedro.lima2@email.com", tamanho_camisa: "G",
    link_rede_social: "—", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Látex",
    contato_emergencia_nome: "Larissa Souza", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua da Praia, 666", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-04-20T07:33:41Z",
  },
  {
    id: "64", nome: "Rafaela Gomes", cpf: "456.789.012-34",
    data_nascimento: "1990-12-12", whatsapp: "(48) 90123-4567",
    email: "rafaela.gomes2@email.com", tamanho_camisa: "M",
    link_rede_social: "@rafaela2", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2020", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Rodrigo Cardoso", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua do Sol, 555", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-012",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-14T10:55:33Z",
  },
  {
    id: "65", nome: "Rodrigo Cardoso", cpf: "567.890.123-45",
    data_nascimento: "2002-08-08", whatsapp: "(48) 91234-5678",
    email: "rodrigo.cardoso2@email.com", tamanho_camisa: "GG",
    link_rede_social: "instagram.com/rodrigo2", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Dipirona",
    contato_emergencia_nome: "Sofia Martins", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua XV de Novembro, 111", bairro: "Centro",
    cidade: "Florianópolis", cep: "88020-345",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-03-15T14:27:18Z",
  },
  {
    id: "66", nome: "Sofia Martins", cpf: "678.901.234-56",
    data_nascimento: "2017-01-01", whatsapp: "(48) 92345-6789",
    email: "sofia.martins2@email.com", tamanho_camisa: "PP",
    link_rede_social: "—", paroquia: "Paróquia São José",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Thiago Ribeiro", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua das Flores, 999", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-456",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-06T08:44:59Z",
  },
  {
    id: "67", nome: "Thiago Ribeiro", cpf: "789.012.345-67",
    data_nascimento: "1994-10-10", whatsapp: "(48) 93456-7890",
    email: "thiago.ribeiro2@email.com", tamanho_camisa: "G",
    link_rede_social: "@thiago2", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Penicilina",
    contato_emergencia_nome: "Ursula Vieira", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua Brasil, 222", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-678",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-08T06:22:14Z",
  },
  {
    id: "68", nome: "Ursula Vieira", cpf: "890.123.456-78",
    data_nascimento: "2016-06-06", whatsapp: "(48) 94567-8901",
    email: "ursula.vieira2@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/ursula2", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Vinícius Paes", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua XV de Novembro, 777", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-789",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-20T07:33:41Z",
  },
  {
    id: "69", nome: "Vinícius Paes", cpf: "901.234.567-89",
    data_nascimento: "2005-04-04", whatsapp: "(48) 95678-9012",
    email: "vinícius.paes2@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Dipirona",
    contato_emergencia_nome: "Wesley Braga", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua das Flores, 333", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-012",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-02-25T11:07:19Z",
  },
  {
    id: "70", nome: "Wesley Braga", cpf: "012.345.678-90",
    data_nascimento: "2012-02-02", whatsapp: "(48) 96789-0123",
    email: "wesley.braga2@email.com", tamanho_camisa: "GG",
    link_rede_social: "@wesley2", paroquia: "Paróquia São José",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Xênia Andrade", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua XV de Novembro, 444", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-345",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-04-12T09:33:27Z",
  },
  {
    id: "71", nome: "Xênia Andrade", cpf: "123.456.789-01",
    data_nascimento: "2004-08-08", whatsapp: "(48) 97890-1234",
    email: "xênia.andrade2@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/xênia2", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Yasmin Sales", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua do Sol, 777", bairro: "Sertão do Ribeirão",
    cidade: "Florianópolis", cep: "88060-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-10T18:22:14Z",
  },
  {
    id: "72", nome: "Yasmin Sales", cpf: "234.567.890-12",
    data_nascimento: "2013-03-03", whatsapp: "(48) 98901-2345",
    email: "yasmin.sales2@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Zélia Tavares", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua das Acácias, 555", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-05-14",
    created_at: "2026-02-14T10:55:33Z",
  },
  {
    id: "73", nome: "Zélia Tavares", cpf: "345.678.901-23",
    data_nascimento: "1985-01-01", whatsapp: "(48) 99012-3456",
    email: "zélia.tavares2@email.com", tamanho_camisa: "G",
    link_rede_social: "@zélia2", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2025", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Amendoim",
    contato_emergencia_nome: "Adriana Melo", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua Brasil, 888", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-012",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-20T07:33:41Z",
  },
  {
    id: "74", nome: "Adriana Melo", cpf: "456.789.012-34",
    data_nascimento: "2006-05-05", whatsapp: "(48) 90123-4567",
    email: "adriana.melo2@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/adriana2", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Bernardo Rezende", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua XV de Novembro, 999", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-456",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-01T15:22:07Z",
  },
  {
    id: "75", nome: "Bernardo Rezende", cpf: "567.890.123-45",
    data_nascimento: "2008-08-08", whatsapp: "(48) 91234-5678",
    email: "bernardo.rezende2@email.com", tamanho_camisa: "G",
    link_rede_social: "@bernardo2", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Penicilina",
    contato_emergencia_nome: "Cecília Figueiredo", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua das Flores, 777", bairro: "Jurerê",
    cidade: "São José", cep: "88120-678",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-28T15:22:07Z",
  },
  {
    id: "76", nome: "Cecília Figueiredo", cpf: "678.901.234-56",
    data_nascimento: "2001-01-01", whatsapp: "(48) 92345-6789",
    email: "cecília.figueiredo2@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/cecília2", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Diego Pinheiro", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua do Sol, 999", bairro: "Barra da Lagoa",
    cidade: "Palhoça", cep: "88130-234",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-02-18T09:55:22Z",
  },
  {
    id: "77", nome: "Diego Pinheiro", cpf: "789.012.345-67",
    data_nascimento: "1999-09-09", whatsapp: "(48) 93456-7890",
    email: "diego.pinheiro2@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Sênior (a partir de 26 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Dipirona",
    contato_emergencia_nome: "Eliane Siqueira", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua XV de Novembro, 555", bairro: "Centro",
    cidade: "São José", cep: "88110-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-24T11:05:17Z",
  },
  {
    id: "78", nome: "Eliane Siqueira", cpf: "890.123.456-78",
    data_nascimento: "1988-04-04", whatsapp: "(48) 94567-8901",
    email: "eliane.siqueira2@email.com", tamanho_camisa: "G",
    link_rede_social: "@eliane2", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Alliance",
    ano_manancial_senior: "2023", tem_sacramento_matrimonio: true,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Fábio Guimarães", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua das Hortênsias, 111", bairro: "Jurerê",
    cidade: "Florianópolis", cep: "88040-890",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-01-12T10:48:12Z",
  },
  {
    id: "79", nome: "Fábio Guimarães", cpf: "901.234.567-89",
    data_nascimento: "2011-11-11", whatsapp: "(48) 95678-9012",
    email: "fábio.guimarães2@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/fábio2", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Amendoim",
    contato_emergencia_nome: "Heloísa Peixoto", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua Brasil, 444", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-123",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-04-30",
    created_at: "2026-03-15T14:27:18Z",
  },
  {
    id: "80", nome: "Heloísa Peixoto", cpf: "012.345.678-90",
    data_nascimento: "2007-07-07", whatsapp: "(48) 96789-0123",
    email: "heloísa.peixoto2@email.com", tamanho_camisa: "M",
    link_rede_social: "@heloísa2", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Igor Barros", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua das Flores, 222", bairro: "Campeche",
    cidade: "Palhoça", cep: "88130-456",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-06T08:33:17Z",
  },
  {
    id: "81", nome: "Igor Barros", cpf: "123.456.789-01",
    data_nascimento: "2005-05-05", whatsapp: "(48) 97890-1234",
    email: "igor.barros2@email.com", tamanho_camisa: "G",
    link_rede_social: "instagram.com/igor2", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Penicilina",
    contato_emergencia_nome: "Juliana Cruz", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua XV de Novembro, 333", bairro: "Jurerê",
    cidade: "São José", cep: "88120-678",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-02-28T12:11:45Z",
  },
  {
    id: "82", nome: "Juliana Cruz", cpf: "234.567.890-12",
    data_nascimento: "2003-03-03", whatsapp: "(48) 98901-2345",
    email: "juliana.cruz2@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Kleber Rangel", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua das Acácias, 777", bairro: "Barra da Lagoa",
    cidade: "Florianópolis", cep: "88060-456",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-02T23:48:37Z",
  },
  {
    id: "83", nome: "Kleber Rangel", cpf: "345.678.901-23",
    data_nascimento: "2009-09-09", whatsapp: "(48) 99012-3456",
    email: "kleber.rangel2@email.com", tamanho_camisa: "GG",
    link_rede_social: "@kleber2", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Dipirona",
    contato_emergencia_nome: "Larissa Souza", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua do Sol, 444", bairro: "Sertão do Ribeirão",
    cidade: "São José", cep: "88110-567",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-12T09:33:27Z",
  },
  {
    id: "84", nome: "Ana Beatriz Lima", cpf: "456.789.012-34",
    data_nascimento: "2018-08-08", whatsapp: "(48) 90123-4567",
    email: "ana.lima2@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/ana2", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "Carlos Eduardo Santos", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua XV de Novembro, 222", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-03-20T07:33:41Z",
  },
  {
    id: "85", nome: "Carlos Eduardo Santos", cpf: "567.890.123-45",
    data_nascimento: "2016-06-06", whatsapp: "(48) 91234-5678",
    email: "carlos.santos2@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Amendoim",
    contato_emergencia_nome: "Fernanda Oliveira", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua das Flores, 555", bairro: "Campeche",
    cidade: "São José", cep: "88120-012",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-24T11:05:17Z",
  },
  {
    id: "86", nome: "Fernanda Oliveira", cpf: "678.901.234-56",
    data_nascimento: "2014-04-04", whatsapp: "(48) 92345-6789",
    email: "fernanda.oliveira2@email.com", tamanho_camisa: "M",
    link_rede_social: "@fernanda2", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Gabriel Henrique Costa", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua XV de Novembro, 777", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-234",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-02-18T09:55:22Z",
  },
  {
    id: "87", nome: "Gabriel Henrique Costa", cpf: "789.012.345-67",
    data_nascimento: "2019-09-09", whatsapp: "(48) 93456-7890",
    email: "gabriel.costa2@email.com", tamanho_camisa: "PP",
    link_rede_social: "instagram.com/gabriel2", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Innocence (5 a 7 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Dipirona",
    contato_emergencia_nome: "Isabela Martins", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua das Acácias, 888", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-456",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-05-10T18:11:09Z",
  },
  {
    id: "88", nome: "Isabela Martins", cpf: "890.123.456-78",
    data_nascimento: "2017-07-07", whatsapp: "(48) 94567-8901",
    email: "isabela.martins2@email.com", tamanho_camisa: "M",
    link_rede_social: "—", paroquia: "Paróquia Santa Clara",
    modalidade: "Manancial Kids (8 a 10 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Penicilina",
    contato_emergencia_nome: "João Pedro Almeida", contato_emergencia_telefone: "(48) 95678-9012",
    endereco: "Rua do Sol, 111", bairro: "Campeche",
    cidade: "Florianópolis", cep: "88040-789",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-03-22T14:18:29Z",
  },
  {
    id: "89", nome: "João Pedro Almeida", cpf: "901.234.567-89",
    data_nascimento: "2002-02-02", whatsapp: "(48) 95678-9012",
    email: "joão.almeida2@email.com", tamanho_camisa: "G",
    link_rede_social: "@joão2", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Power (18 a 25 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Amendoim",
    contato_emergencia_nome: "Larissa Souza", contato_emergencia_telefone: "(48) 96789-0123",
    endereco: "Rua das Hortênsias, 222", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-567",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-04-08T06:22:14Z",
  },
  {
    id: "90", nome: "Larissa Souza", cpf: "012.345.678-90",
    data_nascimento: "2015-05-05", whatsapp: "(48) 96789-0123",
    email: "larissa.souza3@email.com", tamanho_camisa: "P",
    link_rede_social: "instagram.com/larissa3", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Dipirona",
    contato_emergencia_nome: "Lucas Mendes", contato_emergencia_telefone: "(48) 97890-1234",
    endereco: "Rua Brasil, 333", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-789",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-05-06T14:11:37Z",
  },
  {
    id: "91", nome: "Lucas Mendes", cpf: "123.456.789-01",
    data_nascimento: "2013-03-03", whatsapp: "(48) 97890-1234",
    email: "lucas.mendes2@email.com", tamanho_camisa: "GG",
    link_rede_social: "—", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Penicilina",
    contato_emergencia_nome: "Mariana Rocha", contato_emergencia_telefone: "(48) 98901-2345",
    endereco: "Rua XV de Novembro, 444", bairro: "Sertão do Ribeirão",
    cidade: "Palhoça", cep: "88130-012",
    status_inscricao: "Chamado e não aceito", data_recusa_vaga: "2026-05-14",
    created_at: "2026-02-14T10:55:33Z",
  },
  {
    id: "92", nome: "Mariana Rocha", cpf: "234.567.890-12",
    data_nascimento: "2011-11-11", whatsapp: "(48) 98901-2345",
    email: "mariana.rocha3@email.com", tamanho_camisa: "M",
    link_rede_social: "@mariana3", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Matheus Silva", contato_emergencia_telefone: "(48) 99012-3456",
    endereco: "Rua das Flores, 666", bairro: "Jurerê",
    cidade: "São José", cep: "88120-345",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-20T07:33:41Z",
  },
  {
    id: "93", nome: "Matheus Silva", cpf: "345.678.901-23",
    data_nascimento: "2009-09-09", whatsapp: "(48) 99012-3456",
    email: "matheus.silva3@email.com", tamanho_camisa: "G",
    link_rede_social: "instagram.com/matheus3", paroquia: "Paróquia Santa Luzia",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - sem glúten", alergias: "Dipirona",
    contato_emergencia_nome: "Natália Ferreira", contato_emergencia_telefone: "(48) 90123-4567",
    endereco: "Rua XV de Novembro, 555", bairro: "Barra da Lagoa",
    cidade: "Palhoça", cep: "88130-678",
    status_inscricao: "Pediu para excluir da lista", data_recusa_vaga: null,
    created_at: "2026-03-10T18:22:14Z",
  },
  {
    id: "94", nome: "Natália Ferreira", cpf: "456.789.012-34",
    data_nascimento: "2008-08-08", whatsapp: "(48) 90123-4567",
    email: "natália.ferreira3@email.com", tamanho_camisa: "P",
    link_rede_social: "—", paroquia: "Paróquia São Pedro",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Látex",
    contato_emergencia_nome: "Pedro Augusto Lima", contato_emergencia_telefone: "(48) 91234-5678",
    endereco: "Rua das Hortênsias, 777", bairro: "Campeche",
    cidade: "São José", cep: "88120-012",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-06T08:33:17Z",
  },
  {
    id: "95", nome: "Pedro Augusto Lima", cpf: "567.890.123-45",
    data_nascimento: "2010-10-10", whatsapp: "(48) 91234-5678",
    email: "pedro.lima3@email.com", tamanho_camisa: "GG",
    link_rede_social: "@pedro3", paroquia: "Paróquia São Francisco",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - vegetariano", alergias: "Penicilina",
    contato_emergencia_nome: "Rafaela Gomes", contato_emergencia_telefone: "(48) 92345-6789",
    endereco: "Rua XV de Novembro, 333", bairro: "Jurerê",
    cidade: "Palhoça", cep: "88130-456",
    status_inscricao: "Chamado e aceito", data_recusa_vaga: null,
    created_at: "2026-02-28T12:11:45Z",
  },
  {
    id: "96", nome: "Rafaela Gomes", cpf: "678.901.234-56",
    data_nascimento: "2007-07-07", whatsapp: "(48) 92345-6789",
    email: "rafaela.gomes3@email.com", tamanho_camisa: "M",
    link_rede_social: "instagram.com/rafaela3", paroquia: "Paróquia Cristo Rei",
    modalidade: "Manancial New Life (15 a 17 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Não", alergias: "Amendoim",
    contato_emergencia_nome: "Rodrigo Cardoso", contato_emergencia_telefone: "(48) 93456-7890",
    endereco: "Rua do Sol, 555", bairro: "Barra da Lagoa",
    cidade: "São José", cep: "88120-678",
    status_inscricao: "Na fila", data_recusa_vaga: null,
    created_at: "2026-04-12T09:33:27Z",
  },
  {
    id: "97", nome: "Rodrigo Cardoso", cpf: "789.012.345-67",
    data_nascimento: "2012-12-12", whatsapp: "(48) 93456-7890",
    email: "rodrigo.cardoso3@email.com", tamanho_camisa: "G",
    link_rede_social: "—", paroquia: "Paróquia Nossa Senhora",
    modalidade: "Manancial Teens (11 a 13 anos)",
    ano_manancial_senior: null, tem_sacramento_matrimonio: null,
    restricoes_alimentares: "Sim - intolerância à lactose", alergias: "Dipirona",
    contato_emergencia_nome: "Sofia Martins", contato_emergencia_telefone: "(48) 94567-8901",
    endereco: "Rua XV de Novembro, 444", bairro: "Sertão do Ribeirão",
    cidade: "Palhoça", cep: "88130-789",
    status_inscricao: "Já fez o retiro", data_recusa_vaga: null,
    created_at: "2026-05-01T15:22:07Z",
  },
];


export function statusBadgeClass(status: StatusInscricao): string {
  switch (status) {
    case "Na fila": return "bg-amber-100 text-amber-800 border-amber-200";
    case "Chamado e aceito": return "bg-emerald-100 text-emerald-800 border-emerald-200";
    case "Chamado e não aceito": return "bg-rose-100 text-rose-800 border-rose-200";
    case "Já fez o retiro": return "bg-sky-100 text-sky-800 border-sky-200";
    case "Pediu para excluir da lista": return "bg-slate-100 text-slate-700 border-slate-200";
  }
}
// Status ativos: pessoa continua na fila.
const STATUS_NA_FILA: StatusInscricao[] = [
  "Na fila",
  "Chamado e aceito",
  "Chamado e não aceito",
];

export function calcularPosicoesFila(
  retirantes: { id: string; modalidade: string; status_inscricao: StatusInscricao; created_at: string }[],
): Map<string, number> {
  const porModalidade = new Map<string, typeof retirantes>();
  for (const r of retirantes) {
    if (!STATUS_NA_FILA.includes(r.status_inscricao)) continue;
    const arr = porModalidade.get(r.modalidade) ?? [];
    arr.push(r);
    porModalidade.set(r.modalidade, arr);
  }
  const posicoes = new Map<string, number>();
  for (const [, arr] of porModalidade) {
    arr.sort((a, b) => a.created_at.localeCompare(b.created_at));
    arr.forEach((r, i) => posicoes.set(r.id, i + 1));
  }
  return posicoes;
}
